name: riddles_game_ru
description: Riddles Game RU

publish_to: 'none' 


version: 2.0.3+5

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # log
  logger: ^1.1.0

  # local database
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  
  # provider
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  bloc_test: ^9.1.0
  path_provider: ^2.0.11

  # fonts
  google_fonts: ^3.0.1
  auto_size_text: ^3.0.0

  # svg, lotties etc.
  lottie: ^1.4.3
  flutter_svg: ^1.1.5

  # other widgets
  nuts_activity_indicator: ^1.0.0
  top_snackbar_flutter: ^2.1.1
  
  # animations
  animated_digit: ^3.2.1
  animate_do: ^2.1.0

  # feature
  rate_my_app: ^1.1.3
  share_plus: ^6.3.1
  rating_dialog: ^2.0.4
  store_redirect: ^2.0.1
  upgrader: ^6.0.1

  mockito: ^5.3.2
  equatable: ^2.0.5


  cupertino_icons: ^1.0.2
  google_mobile_ads: ^2.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  flutter_gen_runner:
  hive_generator: ^1.1.3
  build_runner:
flutter_gen:
  output: lib/gen/
  colors:
    enabled: true
    inputs:
      - assets/color/color.xml


flutter:

  uses-material-design: true

  assets:
    - assets/color/color.xml
    - assets/data/riddles/
    - assets/data/numbers/
    - assets/data/game/
    - assets/data/img/
    - assets/lotties/
    - assets/i18n/
    - assets/png/
    - assets/svg/

  fonts:
    - family: BalsamiqSans-Regular
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf