import '../../../gen/assets.gen.dart';

List categoriesImage = [
  Assets.data.img.animals.path,
  Assets.data.img.author.path,
  Assets.data.img.berries.path,
  Assets.data.img.birds.path,
  Assets.data.img.family.path,
  Assets.data.img.fish.path,
  Assets.data.img.flowers.path,
  Assets.data.img.food.path,
  Assets.data.img.fruits.path,
  Assets.data.img.heroes.path,
  Assets.data.img.hollidays.path,
  Assets.data.img.insects.path,
  Assets.data.img.letters.path,
  Assets.data.img.mushrooms.path,
  Assets.data.img.music.path,
  Assets.data.img.nature.path,
  Assets.data.img.notes.path,
  Assets.data.img.numbers.path,
  Assets.data.img.objects.path,
  Assets.data.img.professions.path,
  Assets.data.img.seasons.path,
  Assets.data.img.snag.path,
  Assets.data.img.sports.path,
  Assets.data.img.traffic.path,
  Assets.data.img.trees.path,
  Assets.data.img.trick.path,
  Assets.data.img.universe.path,
];
